extends:
  - airbnb
  - plugin:jest/recommended
parser: babel-eslint
parserOptions:
  ecmaVersion: 7
  ecmaFeatures:
    experimentalObjectRestSpread: true
env:
  browser: true
  jest: true
  es6: true
plugins:
  - react
  - jest
  - import
rules:
  arrow-body-style: off
  class-methods-use-this: off
  max-len: off
  no-use-before-define: off
  function-paren-newline: 0
  import/prefer-default-export: 0
  object-curly-newline: off
  comma-dangle: off
  jsx-a11y/label-has-for: 0
  jsx-a11y/anchor-is-valid:
    - error
    - components: -link
  react/jsx-filename-extension:
    - 1
    - extensions:
      - .js
  react/no-did-mount-set-state: 0
  react/prop-types: 0
settings:
  import/resolver:
    webpack:
      config: 'webpack.base.config.js'
